drop table checkbox;
drop table enviados;
drop table radiobox;
drop table text;
drop table respostas;
drop table formularios;
drop table users;
drop table knex_migrations;
drop table knex_migrations_lock