version: '1.0'
name: raeg-api
services:
    api:
        container_name: raeg-api
        image: raeg-api-image:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=https://+:8088
        ports:
          - 80:80