services:
    api:
        container_name: raeg-api
        image: raeg-api-image:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=https://+:8088
        ports:
          - 8088:8088